default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: food_development

test:
  <<: *default
  database: food_test

production:
  url: <%= ENV["DATABASE_URL"] %>