default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

production:
  primary:
    <<: *default

  cable:
    <<: *default

  queue:
    <<: *default

development:
  <<: *default

test:
  <<: *default